# Generated by Django 5.1.1 on 2024-10-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiosMedico',
            fields=[
                ('idestudio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_estudio', models.CharField(choices=[('ORINA', 'Análisis de Orina'), ('ELECTRO', 'Electrocardiograma'), ('ERGOMETRIA', 'Ergometría')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='estudios/')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Estudio Médico',
                'verbose_name_plural': 'Estudios Médicos',
                'db_table': 'estudios_medicos',
            },
        ),
    ]
