# Generated by Django 5.1.1 on 2024-10-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0002_estudiosmedico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiovascular',
            fields=[
                ('idcardiovascular', models.AutoField(primary_key=True, serialize=False)),
                ('auscultacion', models.CharField(blank=True, max_length=45, null=True)),
                ('soplos', models.CharField(blank=True, max_length=45, null=True)),
                ('R1', models.CharField(blank=True, max_length=45, null=True)),
                ('tension_arterial', models.CharField(blank=True, max_length=45, null=True)),
                ('R2', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ruidos_agregados', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen Cardiovascular',
                'verbose_name_plural': 'Exámenes Cardiovasculares',
                'db_table': 'cardiovascular',
            },
        ),
        migrations.CreateModel(
            name='ElectroBasal',
            fields=[
                ('idelectro_basal', models.AutoField(primary_key=True, serialize=False)),
                ('ritmo', models.CharField(blank=True, max_length=45, null=True)),
                ('PQ', models.CharField(blank=True, max_length=45, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=45, null=True)),
                ('arritmias', models.CharField(blank=True, max_length=45, null=True)),
                ('ejeQRS', models.CharField(blank=True, max_length=45, null=True)),
                ('trazadoNormal', models.CharField(blank=True, max_length=45, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Electro Basal',
                'verbose_name_plural': 'Electro Basales',
                'db_table': 'electro_basal',
            },
        ),
        migrations.CreateModel(
            name='ElectroEsfuerzo',
            fields=[
                ('idelectro_esfuerzo', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Electro Esfuerzo',
                'verbose_name_plural': 'Electro Esfuerzos',
                'db_table': 'electro_esfuerzo',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('idlaboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('citologico', models.CharField(blank=True, max_length=45, null=True)),
                ('orina', models.CharField(blank=True, max_length=45, null=True)),
                ('colesterol', models.CharField(blank=True, max_length=45, null=True)),
                ('uremia', models.CharField(blank=True, max_length=45, null=True)),
                ('glucemia', models.CharField(blank=True, max_length=45, null=True)),
                ('otros', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen de Laboratorio',
                'verbose_name_plural': 'Exámenes de Laboratorio',
                'db_table': 'laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Oftalmologico',
            fields=[
                ('idoftalmologico', models.AutoField(primary_key=True, serialize=False)),
                ('od', models.CharField(blank=True, max_length=45, null=True)),
                ('oi', models.CharField(blank=True, max_length=45, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen Oftalmológico',
                'verbose_name_plural': 'Exámenes Oftalmológicos',
                'db_table': 'oftalmologico',
            },
        ),
        migrations.CreateModel(
            name='Torax',
            fields=[
                ('idtorax', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Examen de Tórax',
                'verbose_name_plural': 'Exámenes de Tórax',
                'db_table': 'torax',
            },
        ),
    ]
