# Generated by Django 5.1.1 on 2024-10-29 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0004_registromedico_medico'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromedico',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_medicos', to='persona.jugador'),
        ),
    ]
