# Generated by Django 5.1.1 on 2024-11-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0005_alter_registromedico_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromedico',
            name='fecha_de_llenado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registromedico',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
