# Generated by Django 5.1.1 on 2025-01-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0007_otrosexamenesclinicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardiovascular',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electrobasal',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='electroesfuerzo',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='citologico',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='colesterol',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='glucemia',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='idlaboratorio',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='orina',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='otros',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='uremia',
            field=models.CharField(blank=True, default='', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='otrosexamenesclinicos',
            name='digestivo_observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otrosexamenesclinicos',
            name='osteoarticular_observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otrosexamenesclinicos',
            name='renal_observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='otrosexamenesclinicos',
            name='respiratorio_observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='torax',
            name='observaciones',
            field=models.CharField(blank=True, default='Sin observaciones', max_length=200, null=True),
        ),
    ]
