# Generated by Django 5.1.1 on 2025-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0008_alter_cardiovascular_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='citologico',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='colesterol',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='glucemia',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='idlaboratorio',
            field=models.AutoField(default='S/D', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='orina',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='otros',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='uremia',
            field=models.CharField(blank=True, default='S/D', max_length=45, null=True),
        ),
    ]
