# Generated by Django 5.1.1 on 2025-01-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistroMedico', '0009_alter_laboratorio_citologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='idlaboratorio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
