# Generated by Django 5.1.1 on 2024-10-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RegistroMedico', '0003_cardiovascular_electrobasal_electroesfuerzo_and_more'),
        ('account', '0002_alter_profile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_consultorio', models.CharField(blank=True, max_length=15, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='account.profile')),
                ('registro_medico', models.ManyToManyField(related_name='medicos', to='RegistroMedico.registromedico')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
            },
        ),
    ]
