# Generated by Django 5.1.1 on 2024-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medico', '0002_remove_medico_registro_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
