# Generated by Django 5.1.1 on 2024-12-02 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_profile_rol'),
        ('persona', '0002_torneo_descripcion_torneo_direccion_torneo_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='account.profile')),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='persona.torneo')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representante',
            },
        ),
    ]
